name: Deploy

on:
  push:
    branches:
      - main # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.FIRST_SERVER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > keyfile
          chmod 600 keyfile
          ssh -t -i keyfile ubuntu@ec2-51-20-52-32.eu-north-1.compute.amazonaws.com "sudo bash ~/deploy.sh"
